[package]
name = "contracts"
version = "0.1.0"

[dependencies]
starknet = "2.1.0"
alexandria_math = { path = "../../cairo-ws/alexandria-mangata/src/math/" }
alexandria_substrate = { path = "../../cairo-ws/alexandria-mangata/src/substrate/" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
